- name: Get Allure history
  uses: actions/checkout@v4
  if: always()
  continue-on-error: true
  with:
    ref: gh-pages
    path: gh-pages
- name: Generate Allure Report
  uses: simple-elf/allure-report-action@v1.7
  if: always()
  with:
    allure-history: allure-history
    allure-results: src/allure-results
- name: Publish test report
  uses: peaceiris/actions-gh-pages@v3
  if: always()
  with:
    github_token: ${{ secrets.GITHUB_TOKEN }}
    publish_branch: gh-pages
    publish_dir: allure-history
